#pragma once

#define MAX_VIEWS 32
#define MAX_SHADOW_MAP_CASCADES 8
#define MAX_RELFECTION_PROBES 128
#define MAX_GI_PROBES 128
#define MAX_ENTITIES 1024
#define MAX_POINT_LIGHTS 512
#define MAX_SPOT_LIGHTS 512
#define MAX_DIRECTIONAL_LIGHTS 512
#define MAX_SHADOW_CASTING_POINT_LIGHTS 8
#define MAX_SHADOW_CASTING_SPOT_LIGHTS 8
#define MAX_SHADOW_CASTING_DIRECTIONAL_LIGHTS 8
#define MAX_BONES 100